name: Stable Branch Workflow
on:
  push:
    branches:
      - stable
      - stage

jobs:
  stage-deployment:
    name: Trigger a new stage deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    steps:
      - name: Create new Gitlab pipeline for Shopware 5
        run: |
          curl -XPOST -H "PRIVATE-TOKEN: ${{ secrets.GITLAB_TOKEN }}" "https://gitlab.marmalade.de/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/pipeline?ref=stage"
  release:
    name: Create a new release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stable'
    steps:
      - name: Clone code repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install npm dependencies
        run: yarn

      - name: Semantic release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

          GIT_AUTHOR_NAME: ${{ secrets.GIT_USERNAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_USERNAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
